### ISSUE TITLE
alternative install

### ISSUE THREAD

**Issue by laurencowley** [jhawkey/IS_mapper#28]
Hi Jane,
We are trying to install the latest version of ismapper on the phe cluster to be able to run multiple samples in parallel but can't use pip to install as we use shared storage and pip install installs ismaper to user bin. Is there any alternative installs that you can suggest?
Thanks!

**Comment by jhawkey** [comment]
Hi @laurencowley,

When I was developing ISMapper, I put some arguments in the scripts to allow me to run ISMapper without it being installed.

It's a bit messy (because I was new to programming at the time), but it works!

Just download the IS_mapper git repository to wherever you you would like. Instead of installing with pip (which places the scripts in user bin), instead just run the ismap.py script directly from that directory. So that ismap.py knows where to go to look for the other scripts, provide the `--path` argument. This needs to point to the `scripts/` folder inside the ISMapper repo.

So:
```python /path/to/folder/scripts/ismap.py --reads *.fastq.gz --queries IS.fasta --typingRef ref.gbk --type typing --log --path /path/to/folder/scripts```

I'm not sure if you use a slurm queuing system, but if you do, the wrapper script `slurm_ismap.py` works in a similar way. Provide the `--path` option inside `--other_args`. You will also need to supply `--script` to slurm_ismap.py, which is the full path to `ismap.py`.

So:
```python /path/to/folder/scripts/slurm_ismap.py --reads *.fastq.gz --queries IS.fasta --runtype typing --logprefix test --script /path/to/folder/scripts/ismap.py --other_args "--path path/to/folder/scripts --typingRef ref.gbk --log"```

I don't know of any other official installs. Apparently pip install can be used to install the package into a different directory to user bin, but I'm not sure if this is suitable for your purposes. [This Stack Overflow thread describes the process](https://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip).

Hopefully that is helpful!

**Comment by laurencowley** [comment]
Perfect, thanks Jane!
