### ISSUE TITLE
create_genbank_table.py arguments

### ISSUE THREAD

**Issue by logan-fink** [jhawkey/IS_mapper#31]
Hello!  I am trying to use your software to help improve assemblies on short-read sequencing data for an organism with many IS elements.  

I run the following command:

ismap --reads CO14-1449_S6_L001_1.fastq.gz CO14-1449_S6_L001_2.fastq.gz --queries common_Ft_IS_elements.fasta --assemblies CO14-1449_S6_L001_assembly.fasta --assemblyid _assembly --extension .fasta --type fasta --runtype improvement --output CO14-1449_S6_L001_out

But I receive this error output:

 usage: create_genbank_table.py [-h] --five_bed FIVE_BED --three_bed THREE_BED
                               --assembly ASSEMBLY --type TYPE --output OUTPUT
create_genbank_table.py: error: argument --five_bed is required
Traceback (most recent call last):
  File "/usr/local/bin/ismap", line 11, in <module>
    load_entry_point('ISMapper==0.1.5.1', 'console_scripts', 'ismap')()
  File "/usr/local/lib/python2.7/dist-packages/ismap/ismap.py", line 645, in main
    run_command([args.path + 'create_genbank_table.py', '--left_bed', left_merged_bed, '--right_bed', right_merged_bed, '--assembly', assembly, '--type fasta', '--output', current_dir + sample + '_' + query_name], shell=True)
  File "/usr/local/lib/python2.7/dist-packages/ismap/ismap.py", line 150, in run_command
    raise CommandError({"message": message})
ismap.ismap.CommandError: {'message': "Command 'create_genbank_table.py --left_bed /home/staphb/seq_downloads/testing/is_map_test/ERR225612_left_ISSsu3_merged.sorted.bed --right_bed /home/staphb/seq_downloads/testing/is_map_test/ERR225612_right_ISSsu3_merged.sorted.bed --assembly ERR225612_assembly.fasta --type fasta --output /home/staphb/seq_downloads/testing/is_map_test/ERR225612_ISSsu3' failed with non-zero exit status: 2"}

I think that this is because ismap.py is trying to execute create_genbank_table.py using the parameters --left_bed and --right_bed, whereas the parameters the script is looking for are called --five_bed and --three_bed.  I'm going to try modifying the code locally and I can let you know how that works out, but I thought you should know!  

Thanks!

**Comment by jhawkey** [comment]
Hi Logan,

Yes, that sounds like the issue. Thanks for spotting the error!

I am currently working on a version 2 of ISMapper, so this error will be
fixed in the new version.


On 3 February 2018 at 9:15:53 am, Logan Fink (notifications@github.com)
wrote:

Hello! I am trying to use your software to help improve assemblies on
short-read sequencing data for an organism with many IS elements.

I run the following command:

ismap --reads CO14-1449_S6_L001_1.fastq.gz CO14-1449_S6_L001_2.fastq.gz
--queries common_Ft_IS_elements.fasta --assemblies
CO14-1449_S6_L001_assembly.fasta --assemblyid _assembly --extension .fasta
--type fasta --runtype improvement --output CO14-1449_S6_L001_out

But I receive this error output:

usage: create_genbank_table.py [-h] --five_bed FIVE_BED --three_bed
THREE_BED
--assembly ASSEMBLY --type TYPE --output OUTPUT
create_genbank_table.py: error: argument --five_bed is required
Traceback (most recent call last):
File "/usr/local/bin/ismap", line 11, in
load_entry_point('ISMapper==0.1.5.1', 'console_scripts', 'ismap')()
File "/usr/local/lib/python2.7/dist-packages/ismap/ismap.py", line 645, in
main
run_command([args.path + 'create_genbank_table.py', '--left_bed',
left_merged_bed, '--right_bed', right_merged_bed, '--assembly', assembly,
'--type fasta', '--output', current_dir + sample + '_' + query_name],
shell=True)
File "/usr/local/lib/python2.7/dist-packages/ismap/ismap.py", line 150, in
run_command
raise CommandError({"message": message})
ismap.ismap.CommandError: {'message': "Command 'create_genbank_table.py
--left_bed
/home/staphb/seq_downloads/testing/is_map_test/ERR225612_left_ISSsu3_merged.sorted.bed
--right_bed
/home/staphb/seq_downloads/testing/is_map_test/ERR225612_right_ISSsu3_merged.sorted.bed
--assembly ERR225612_assembly.fasta --type fasta --output
/home/staphb/seq_downloads/testing/is_map_test/ERR225612_ISSsu3' failed
with non-zero exit status: 2"}

I think that this is because ismap.py is trying to execute
create_genbank_table.py using the parameters --left_bed and --right_bed,
whereas the parameters the script is looking for are called --five_bed and
--three_bed. I'm going to try modifying the code locally and I can let you
know how that works out, but I thought you should know!

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhawkey/IS_mapper/issues/31>, or mute the thread

**Comment by jhawkey** [comment]
Hi Anita,
Thanks for pushing a fix for this! 

I am actually release version 2 of ISMapper today so hopefully that will fix any other issues you're having. :)
