### ISSUE TITLE
How to run this????  It shows error

### ISSUE THREAD

**Issue by GuptaTanay** [jhawkey/IS_mapper#34]
Hey there, 
no doubt you have provided a great Readme, I have managed to download all the dependencies required for this software. But while running, I am facing error in the ismap.py script.

1. print function doesn't contain (parentheses) for its arguments. As I am a software developer and comfortable with python. But after correcting this error.
Now I am getting an error saying ->  No module named 'resources' found, which means that the script cannot find the resource module.
So please tell me what to do and how???

It will also be great If you help me with more brief information about what are the actual parameters of the command through the command line. So that I can run this software without any problem.

Thanks in advamce!

**Comment by jhawkey** [comment]
Hi,

ISMapper is written in Python 2, which doesn't require parentheses for print statements. If you have edited the code yourself then unfortunately I'm unable to assist you because I don't know what changes you have made.

The resource module is installed with Python 2, so perhaps you are using the wrong version of Python.

The parameters for the software, with their descriptions and examples, are located in the readme file. You can also see all parameters and brief descriptions by running `ismap.py -h` on the command line.
