### ISSUE TITLE
ISs inserted into other ISs

### ISSUE THREAD

**Issue by SamuelGreenrod** [jhawkey/IS_mapper#50]
Hi there,

Many of the IS hits I get in my analyses appear to be intra-IS insertions (e.g insertion is labelled as disrupting an IS transposase). I was wondering if you could comment on whether these hits can be trusted. For example, if an IS is found to disrupt another IS (e.g insertion is found to disrupt a transposase), and the IS is present in the reference in multiple copies, would ISMapper suggest that all copies of the IS contain the disruption? My thinking is the reads that map to a transposase will map to all copies throughout the reference. Therefore, I'm hesitant to trust these as true hits and am considering dropping them. What do you think? Thanks.

Sam

**Comment by jhawkey** [comment]
Hi Sam,

If the IS that your query IS is inside is present in only one copy (and you are confident of that), then I think you can trust the hit. However, if the IS is present in multiple copies then yes, ISMapper will report multiple hits as the flanking reads will map randomly to whatever copy of the IS it can find. I believe one of the figures in the paper shows what happens when the IS is flanked by a repeat? I agree that you probably shouldn't trust those hits!
